apiVersion: v1
kind: Pod
metadata:
     labels:
       some-label: some-label-value
spec:
  containers:
    - name: docker-build
      image: docker
      command:
       - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
    - name: docker-build1
      image: pavan123456788/demo1:v7
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - hostPath:
         path: /var/run/docker.sock
      name: docker-sock
