apiVersion: v1
kind: Pod
metadata:
     labels:
       some-label: jenkins-slave
spec:
  containers:
    - name: docker-build1
      image: pavan123456788/demo1:v14
      command:
      - sleep
      args:
      - 99d
      tty: true
      resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 410m
            memory: 512Mi
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - hostPath:
         path: /var/run/docker.sock
      name: docker-sock
